/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Schemaversion = "0.3";
export type Question = string;
export type Concept = string;
export type Focus = string;
export type Level = "beginner" | "intermediate" | "advanced";
export type Timesensitive = boolean;
/**
 * @minItems 1
 */
export type Keypoints = [KeyPoint, ...KeyPoint[]];
export type Id = string;
export type Text = string;
/**
 * Source ids; required when the lesson is time-sensitive.
 */
export type Sources = string[];
export type Id1 = string;
export type Text1 = string;
export type Misconceptions = Misconception[];
export type Id2 = string;
export type Title = string;
export type Url = string;
export type Sources1 = Source[];
export type Id3 = string;
export type Label = string;
export type Definition = string;
export type Terms = Term[];
/**
 * @minItems 1
 */
export type Scenes = [ScrollyScene | ExploreScene | StackScene, ...(ScrollyScene | ExploreScene | StackScene)[]];
export type Layout = "scrolly";
export type Id4 = string;
export type Title1 = string;
export type Visual =
  | DiagramVisual
  | SequenceVisual
  | CompareVisual
  | FunctionPlotVisual
  | MatrixVisual
  | DistributionVisual
  | PointCloudVisual;
export type Widget = "Diagram";
/**
 * @minItems 2
 * @maxItems 12
 */
export type Nodes = [Node, Node, ...Node[]];
export type Id5 = string;
export type Label1 = string;
export type Group = string | null;
export type Id6 = string;
export type From = string;
export type To = string;
export type Label2 = string | null;
/**
 * @maxItems 20
 */
export type Edges = Edge[];
export type Id7 = string;
export type Label3 = string;
/**
 * @maxItems 4
 */
export type Groups = Group1[];
export type Widget1 = "Sequence";
/**
 * @minItems 2
 * @maxItems 6
 */
export type Actors = [Actor, Actor, ...Actor[]];
export type Id8 = string;
export type Label4 = string;
/**
 * @minItems 1
 * @maxItems 16
 */
export type Messages = [Message, ...Message[]];
export type Id9 = string;
export type From1 = string;
export type To1 = string;
export type Text2 = string;
export type Widget2 = "Compare";
/**
 * @minItems 2
 * @maxItems 4
 */
export type Columns = [Column, Column, ...Column[]];
export type Id10 = string;
export type Title2 = string;
/**
 * @minItems 1
 * @maxItems 8
 */
export type Rows = [Row, ...Row[]];
export type Label5 = string;
export type Cells = string[];
export type Widget3 = "FunctionPlot";
/**
 * y as a function of x and the parameters, e.g. 'a * x^2 + b'.
 */
export type Expression = string;
export type Label6 = string;
export type Min = number;
export type Max = number;
/**
 * An identifier other than x.
 */
export type Name = string;
export type Label7 = string;
export type Min1 = number;
export type Max1 = number;
/**
 * @maxItems 4
 */
export type Params = Param[];
export type Widget4 = "Matrix";
export type Props = SoftmaxRecipe | DotProductRecipe | ConfusionRecipe;
export type Recipe = "softmax";
/**
 * @minItems 1
 * @maxItems 8
 */
export type Rows1 = [string, ...string[]];
/**
 * @minItems 2
 * @maxItems 8
 */
export type Cols = [string, string, ...string[]];
/**
 * Raw scores, one row per row label; each row is softmaxed.
 */
export type Scores = number[][];
export type Recipe1 = "dot-product";
/**
 * @minItems 1
 * @maxItems 8
 */
export type Rows2 = [Vector, ...Vector[]];
export type Label8 = string;
/**
 * @minItems 1
 * @maxItems 8
 */
export type Values = [number, ...number[]];
/**
 * @minItems 1
 * @maxItems 8
 */
export type Cols1 = [Vector, ...Vector[]];
export type Recipe2 = "confusion";
/**
 * @minItems 2
 * @maxItems 6
 */
export type Classes = [string, string, ...string[]];
/**
 * Class index per example.
 *
 * @minItems 1
 * @maxItems 200
 */
export type Actual = [number, ...number[]];
/**
 * Class index per example.
 *
 * @minItems 1
 * @maxItems 200
 */
export type Predicted = [number, ...number[]];
export type Widget5 = "Distribution";
/**
 * One per option, e.g. candidate next tokens.
 *
 * @minItems 2
 * @maxItems 12
 */
export type Labels = [string, string, ...string[]];
/**
 * Illustrative raw scores, one per label. The browser computes probabilities.
 */
export type Logits = number[];
/**
 * Index of the correct label, for cross-entropy. Optional.
 */
export type Target = number | null;
export type Widget6 = "PointCloud";
/**
 * blobs/moons/circles/xor are labelled classes; line/curve are regression data (classes 1).
 */
export type Shape = "blobs" | "moons" | "circles" | "xor" | "line" | "curve";
/**
 * Number of points; a random quarter of them is held out as test data.
 */
export type N = number;
export type Noise = number;
/**
 * 1 for line/curve; 2 for moons/circles/xor; 2 or 3 for blobs.
 */
export type Classes1 = number;
/**
 * Same seed, same points, for every learner.
 */
export type Seed = number;
export type Xlabel = string;
export type Ylabel = string;
/**
 * One short name per class, e.g. ['spam', 'not spam'].
 */
export type Classlabels = string[];
export type Model = "none" | "linear" | "polynomial" | "logistic" | "knn" | "kmeans";
/**
 * @minItems 1
 * @maxItems 8
 */
export type Steps = [Step, ...Step[]];
export type Id11 = string;
/**
 * 30 to 80 words, one idea. Markup: [[part:id|label]], [[term:id|label]], [[source:id|label]], {stateKey} prints a state value, {fact:name} prints a value the widget computed.
 */
export type Text3 = string;
/**
 * Widget part ids.
 */
export type Highlight = string[];
/**
 * Key point ids.
 */
export type Covers = string[];
/**
 * A part id of the scene's widget; the note is drawn next to it.
 */
export type Anchor = string;
/**
 * Plain text; may print {fact:name} or {stateKey}.
 */
export type Text4 = string;
/**
 * Short notes pinned to widget parts.
 *
 * @maxItems 3
 */
export type Annotate = Annotation[];
export type Layout1 = "explore";
export type Id12 = string;
export type Title3 = string;
export type Visual1 =
  | DiagramVisual
  | SequenceVisual
  | CompareVisual
  | FunctionPlotVisual
  | MatrixVisual
  | DistributionVisual
  | PointCloudVisual;
export type Kind = "slider";
export type Key = string;
export type Label9 = string;
export type Min2 = number;
export type Max2 = number;
export type Step1 = number | null;
export type Kind1 = "select";
export type Key1 = string;
export type Label10 = string;
/**
 * @minItems 2
 */
export type Options = [
  boolean | number | number | string | null,
  boolean | number | number | string | null,
  ...(boolean | number | number | string | null)[]
];
export type Controls = (Slider | Select)[];
export type Task = string;
export type Layout2 = "stack";
export type Id13 = string;
export type Title4 = string;
/**
 * @minItems 1
 */
export type Blocks = [Prose | Cards | Predict | Sort, ...(Prose | Cards | Predict | Sort)[]];
export type Type = "prose";
export type Text5 = string;
export type Covers1 = string[];
export type Type1 = "cards";
/**
 * @minItems 1
 * @maxItems 4
 */
export type Items = [Card, ...Card[]];
export type Title5 = string;
export type Body = string;
export type Tag = string | null;
export type Covers2 = string[];
export type Type2 = "predict";
export type Question1 = string;
/**
 * @minItems 2
 * @maxItems 5
 */
export type Options1 = [string, string, ...string[]];
/**
 * Index into options.
 */
export type Answer = number;
export type Hint = string;
export type Explanation = string;
export type Misconception1 = string;
export type Covers3 = string[];
export type Type3 = "sort";
export type Question2 = string;
/**
 * @minItems 2
 * @maxItems 8
 */
export type Items1 = [string, string, ...string[]];
/**
 * @minItems 2
 * @maxItems 4
 */
export type Buckets = [string, string, ...string[]];
/**
 * Bucket index for each item, in item order.
 */
export type Answer1 = number[];
export type Hint1 = string;
export type Explanation1 = string;
export type Misconception2 = string;
export type Covers4 = string[];

export interface Lesson {
  schemaVersion: Schemaversion;
  question: Question;
  concept: Concept;
  focus: Focus;
  level: Level;
  timeSensitive: Timesensitive;
  keyPoints: Keypoints;
  misconceptions: Misconceptions;
  sources: Sources1;
  terms: Terms;
  scenes: Scenes;
}
export interface KeyPoint {
  id: Id;
  text: Text;
  sources: Sources;
}
export interface Misconception {
  id: Id1;
  text: Text1;
}
export interface Source {
  id: Id2;
  title: Title;
  url: Url;
}
export interface Term {
  id: Id3;
  label: Label;
  definition: Definition;
}
export interface ScrollyScene {
  layout: Layout;
  id: Id4;
  title: Title1;
  visual: Visual;
  state: State;
  steps: Steps;
}
export interface DiagramVisual {
  widget: Widget;
  props: DiagramProps;
}
export interface DiagramProps {
  nodes: Nodes;
  edges: Edges;
  groups: Groups;
}
export interface Node {
  id: Id5;
  label: Label1;
  group: Group;
}
export interface Edge {
  id: Id6;
  from: From;
  to: To;
  label: Label2;
}
export interface Group1 {
  id: Id7;
  label: Label3;
}
export interface SequenceVisual {
  widget: Widget1;
  props: SequenceProps;
}
export interface SequenceProps {
  actors: Actors;
  messages: Messages;
}
export interface Actor {
  id: Id8;
  label: Label4;
}
export interface Message {
  id: Id9;
  from: From1;
  to: To1;
  text: Text2;
}
export interface CompareVisual {
  widget: Widget2;
  props: CompareProps;
}
export interface CompareProps {
  columns: Columns;
  rows: Rows;
}
export interface Column {
  id: Id10;
  title: Title2;
}
export interface Row {
  label: Label5;
  cells: Cells;
}
export interface FunctionPlotVisual {
  widget: Widget3;
  props: FunctionPlotProps;
}
export interface FunctionPlotProps {
  expression: Expression;
  x: Axis;
  /**
   * Omit to fit the y axis to the curve.
   */
  y: Axis | null;
  params: Params;
}
export interface Axis {
  label: Label6;
  min: Min;
  max: Max;
}
export interface Param {
  name: Name;
  label: Label7;
  min: Min1;
  max: Max1;
}
export interface MatrixVisual {
  widget: Widget4;
  props: Props;
}
export interface SoftmaxRecipe {
  recipe: Recipe;
  rows: Rows1;
  cols: Cols;
  scores: Scores;
}
export interface DotProductRecipe {
  recipe: Recipe1;
  rows: Rows2;
  cols: Cols1;
}
export interface Vector {
  label: Label8;
  values: Values;
}
export interface ConfusionRecipe {
  recipe: Recipe2;
  classes: Classes;
  actual: Actual;
  predicted: Predicted;
}
export interface DistributionVisual {
  widget: Widget5;
  props: DistributionProps;
}
export interface DistributionProps {
  labels: Labels;
  logits: Logits;
  target: Target;
}
export interface PointCloudVisual {
  widget: Widget6;
  props: PointCloudProps;
}
export interface PointCloudProps {
  dataset: Dataset;
  xLabel: Xlabel;
  yLabel: Ylabel;
  classLabels: Classlabels;
  model: Model;
}
export interface Dataset {
  shape: Shape;
  n: N;
  noise: Noise;
  classes: Classes1;
  seed: Seed;
}
/**
 * Default value for every state key the widget reads.
 */
export interface State {
  [k: string]: boolean | number | string | null;
}
export interface Step {
  id: Id11;
  text: Text3;
  set: Set;
  highlight: Highlight;
  covers: Covers;
  annotate: Annotate;
}
/**
 * State changes on top of the scene defaults; not accumulated from earlier steps.
 */
export interface Set {
  [k: string]: boolean | number | string | null;
}
export interface Annotation {
  anchor: Anchor;
  text: Text4;
}
export interface ExploreScene {
  layout: Layout1;
  id: Id12;
  title: Title3;
  visual: Visual1;
  state: State1;
  controls: Controls;
  task: Task;
}
/**
 * Default value for every state key the widget reads.
 */
export interface State1 {
  [k: string]: boolean | number | string | null;
}
export interface Slider {
  kind: Kind;
  key: Key;
  label: Label9;
  min: Min2;
  max: Max2;
  step: Step1;
}
export interface Select {
  kind: Kind1;
  key: Key1;
  label: Label10;
  options: Options;
}
export interface StackScene {
  layout: Layout2;
  id: Id13;
  title: Title4;
  blocks: Blocks;
}
export interface Prose {
  type: Type;
  text: Text5;
  covers: Covers1;
}
export interface Cards {
  type: Type1;
  items: Items;
  covers: Covers2;
}
export interface Card {
  title: Title5;
  body: Body;
  tag: Tag;
}
export interface Predict {
  type: Type2;
  question: Question1;
  options: Options1;
  answer: Answer;
  hint: Hint;
  explanation: Explanation;
  misconception: Misconception1;
  covers: Covers3;
}
export interface Sort {
  type: Type3;
  question: Question2;
  items: Items1;
  buckets: Buckets;
  answer: Answer1;
  hint: Hint1;
  explanation: Explanation1;
  misconception: Misconception2;
  covers: Covers4;
}
